name = "wikipedia-telegram-bot"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Türkiye Saatiyle (UTC+3) 10:00, 12:00, 14:00, 16:00, 18:00, 20:00
[triggers]
crons = ["0 6,8,10,12,14,16,18 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "wikipedia_bot_db"
database_id = "280a42a3-fc8c-4968-905b-cd905b32e818"
